### login user
POST http://localhost:9090/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "1234"
}

### login admin
POST http://localhost:9090/auth/login
Content-Type: application/json

{
  "email": "admin1@gmail.com",
  "password": "1234"
}

### register admin
POST http://localhost:9090/auth/register
Content-Type: application/json

{
  "role": "ADMIN",
  "firstname": "admin1",
  "lastname": "admin1",
  "email": "admin1@gmail.com",
  "password": "1234"
}

### register user
POST http://localhost:9090/auth/register
Content-Type: application/json

{
  "role": "USER",
  "firstname": "user",
  "lastname": "user",
  "email": "user@gmail.com",
  "password": "1234"
}

### get
GET http://localhost:9090/demo/get1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYW1lQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY4Mjk1NiwiZXhwIjoxNzEyNjg0NDkyfQ.QG14KMV-GEDuyECDhFoD50fJYrhtmijqMyxXujHd8tfHNyGSEZ5j3caES7FZcRZx
