POST http://localhost:9090/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "1234"
}

###
POST http://localhost:9090/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "firstname",
  "lastname": "lastname",
  "email": "email@gmail.com",
  "password": "1234"
}

###
GET http://localhost:9090/api/v1/demo-controller
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE3MTIyNDY4NzEsImV4cCI6MTcxMjI0ODQwN30.GTicoB0GnfDxICZW_N-OH1IpYRkMX3jo5QyRfRW99aU
###
